version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - homework-network
    command: /bin/bash -c "apt-get update && apt-get install -y default-mysql-client && nginx -g 'daemon off;'"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: erika
      MYSQL_DATABASE: database-homework
      MYSQL_PASSWORD: erika
    networks:
      - homework-network

networks:
  homework-network:
    driver: bridge
